//
//  JVChatTabItem.swift
//  Colloquy (Old)
//
//  Created by C.W. Betts on 1/26/16.
//
//

import Cocoa

#if false
class JVChatTabItem: NSTabViewItem, AICustomTabViewItem {
	let chatViewController: JVChatViewController
	init(chatViewController controller: JVChatViewController) {
		self.chatViewController = controller
		super.init(identifier: controller.identifier)
	}

	required init?(coder aDecoder: NSCoder) {
	    fatalError("init(coder:) has not been implemented")
	}
	
	override var label: String {
		get {
			return chatViewController.title()
		}
		set {
			
		}
	}
	
	var icon: NSImage {
		var active = chatViewController.icon()
		if let anActive = chatViewController.statusImage?() {
			active = anActive
		}
		
		if active.size.width > 16.0 || active.size.height > 16.0 {
			let ret = active.copy() as! NSImage
			ret.size = NSSize(width: 16, height: 16)
			active = ret;
		}
		
		return active
	}
	
	@objc(isEnabled) var enabled: Bool {
		let controller = chatViewController as AnyObject
		if let aBool = controller.isEnabled?() {
			return aBool
		}
		return true
	}
	
	override var initialFirstResponder: NSView? {
		get {
			return (chatViewController.firstResponder() ?? chatViewController.view()) as? NSView
		}
		set {
			
		}
	}
	/*
- (void) _setInitialFirstResponder:(id) first autoGenerated:(BOOL) au {
// This locks us up when un-hiding the application, not sure why. Not calling super fixes it.
// [super _setInitialFirstResponder:first autoGenerated:au];
}
*/
}

#endif
